# Generated by Django 4.0.1 on 2022-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=100000, editable=False, null=True),
        ),
    ]
