# Generated by Django 4.0.1 on 2022-02-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
    ]
