# Generated by Django 4.0.1 on 2022-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_option',
            field=models.BooleanField(default=False),
        ),
    ]
